services:
  api:
    container_name: flask-application
    image: 0rf1az/flask-application:latest
    command: sh scripts/runner.sh
    build:
      context: api
      args:
        REQUESTS_VERSION: 2.32.4
    environment:
      - DEBUG=false
    env_file:
      - api/.env
    restart: on-failure
    ports:
      - 8888:5001
    networks:
      - full-stack
    develop:
      watch:
        - path: ./api
          target: /code
          action: sync
        - path: ./api/requirements.txt
          action: rebuild
          # include: main.py
    secrets:
      - db_password
    # volumes:
    #   - ./api:/code
    # depends_on:
    #   - db
  db:
    container_name: mysql
    image: mysql:8.0.25
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_password
      - MYSQL_DATABASE=flask-application
      - MYSQL_USER=api
      - MYSQL_PASSWORD=api
    ports:
      - 3306:3306
    networks:
      - full-stack
    # volumes:
    #   - db-data:/var/lib/mysql
    secrets:
      - db_password

networks:
  full-stack: {}

volumes:
  db-data: {}

# configs:

secrets:
  db_password:
    environment: "password"
  db_api_password:
    environment: "db_api_password"


