version: "3.9"
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    command: bash scripts/runner.sh
    ports:
      - 5051:5000
    volumes:
      - ./api:/app/api
    depends_on:
      - db
    restart: on-failure:10
    healthcheck:
      test: curl --fail http://localhost:5000/api/users
      start_period: 2s
    networks:
      - mycoolwebapp
    secrets:
      - db_password

  db:
    image: mysql:8.0.25
    restart: on-failure:10
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - 33066:3306
    networks:
      - mycoolwebapp
    secrets:
      - db_password

secrets:
  db_password: 
    file: ../pass.txt


networks:
  mycoolwebapp:
